package rules;

import com.example.riskcontrol.model.LoginEvent
import com.example.riskcontrol.service.DimensionService
import com.example.riskcontrol.model.EnumTimePeriod

global DimensionService dimensionService

rule "96_login_openid"
    salience 96
    lock-on-active true
    when
        event:LoginEvent(openId!=null)
    then
        int count  = dimensionService.distinctCount(event,new String[]{LoginEvent.OPENID},EnumTimePeriod.LASTWEEK,LoginEvent.MOBILE);
        if(event.addScore(count,5,10,1)){
            dimensionService.insertRiskEvent(event,"同一个openid切换手机号登录，7天内大于等于5个账号,count="+count);
        }

end