package rules;

import com.example.riskcontrol.model.Event
import com.example.riskcontrol.service.BlackListService
import com.example.riskcontrol.model.BlackList
import com.example.riskcontrol.service.DimensionService

global BlackListService blackListService
global DimensionService dimensionService

rule "994_all_black_openid"
    salience 994
    lock-on-active true
    when
          event:Event(openId!=null)
    then
        if(blackListService.contain(BlackList.EnumDimension.OPENID,BlackList.EnumType.WHITE,event.getOpenId())){
            dimensionService.insertEvent(event);
            delete(event);
        }

        if(blackListService.contain(BlackList.EnumDimension.OPENID,BlackList.EnumType.BLACK,event.getOpenId())){
            event.setScore(100);
            dimensionService.insertEvent(event);
            dimensionService.insertRiskEvent(event,"黑名单设备id");
            delete(event);
        }
end