package rules;

import com.example.riskcontrol.model.Event
import com.example.riskcontrol.service.BlackListService
import com.example.riskcontrol.model.BlackList
import com.example.riskcontrol.service.DimensionService

global BlackListService blackListService
global DimensionService dimensionService

rule "995_all_black_device"
    salience 995
    lock-on-active true
    when
          event:Event(deviceId!=null)
    then
        if(blackListService.contain(BlackList.EnumDimension.DEVICEID,BlackList.EnumType.WHITE,event.getDeviceId())){
            dimensionService.insertEsEvent(event);
            delete(event);
        }

        if(blackListService.contain(BlackList.EnumDimension.DEVICEID,BlackList.EnumType.BLACK,event.getDeviceId())){
            event.setScore(100);
            dimensionService.insertEsEvent(event);
            dimensionService.insertRiskEvent(event,"黑名单设备id");
            delete(event);
        }
end