package rules;

import com.example.riskcontrol.model.Event
import com.example.riskcontrol.service.BlackListService
import com.example.riskcontrol.model.BlackList
import com.example.riskcontrol.service.DimensionService

global BlackListService blackListService
global DimensionService dimensionService

rule "996_all_black_mobile"
    salience 996
    lock-on-active true
    when
          event:Event()
    then
        if(blackListService.contain(BlackList.EnumDimension.MOBILE,BlackList.EnumType.WHITE,event.getMobile())){
            dimensionService.insertEsEvent(event);
            delete(event);
        }

        if(blackListService.contain(BlackList.EnumDimension.MOBILE,BlackList.EnumType.BLACK,event.getMobile())){
            event.setScore(100);
            dimensionService.insertEsEvent(event);
            dimensionService.insertRiskEvent(event,"黑名单手机号");
            delete(event);
        }
end